version: "3.7"

volumes:
  laravel_database:
  mongodb-data: {}
networks:
  laravel_network:
services:
  app:
    container_name: laravel_app
    build:
      context: ./
      dockerfile: DockerFile
    ports:
      - "8079:80"
    volumes:
      - "./:/var/www/laravel"
      - "./docker/laravel.conf:/etc/apache2/sites-available/000-default.conf"
      - "./docker/php.ini:/usr/local/etc/php/php.ini"
    networks:
      - laravel_network
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: laravel_db
    ports:
      - "3307:3306"
    volumes:
      - "laravel_database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: laravel2024!
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: laravel
    networks:
      - laravel_network
  redis:
    image: redis:7.2-alpine
    container_name: laravel_redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=laravel
      - REDIS_PORT=6379
    networks:
      - laravel_network
  phpmyadmin:
       image: phpmyadmin/phpmyadmin
       container_name: laravel_phpmyadmin
       ports:
           - "8081:80"
       volumes:
           - "./docker/phpmyadmin.ini:/usr/local/etc/php/php.ini"
       environment:
           PMA_ARBRITARY: 1
           PMA_HOST: db
       networks:
           - laravel_network
  mongo:
       image: mongo:4.4.12
       ports:
        - "27017:27017"
       volumes:
        - mongodb-data:/data/db
       container_name: laravel_mongo_db
       networks:
        - laravel_network
